---
- name: Setup the Mesos Masters
  hosts: master
  vars_files:
    - vars/mesos.yml
  roles:
    - role: mesos_master
      tags: [mesos_master, mesos, app]
      bind_interface: enp0s8

    - role: marathon
      tags: [marathon, mesos, app]
      bind_interface: enp0s8

    - role: chronos
      tags: [chronos, mesos, app]
      bind_interface: enp0s8