---
consul_version: '0.6.3'
consul_package: "{{ consul_packages[consul_version][ansible_system][ansible_architecture] }}"
consul_package_name: "{{ consul_package.name }}"
consul_package_checksum: "{{ consul_package.sha256sum }}"
consul_package_repository: https://releases.hashicorp.com/consul
consul_package_url: "{{ consul_package_repository }}/{{ consul_version }}/{{ consul_package_name }}"

consul_group: consul
consul_user: consul
consul_install_path: '/usr/local/bin'
consul_data_path: '/opt/consul'
consul_config_path: '/etc/consul.d'

consul_install_mode: 'client'

consul_conf_advertise_addr: "{{ hostvars[inventory_hostname]['ansible_' + bind_interface].ipv4.address }}"
consul_conf_datacenter: 'ming_latitude'
consul_conf_bind_addr: 0.0.0.0
consul_conf_client_addr: 127.0.0.1
consul_conf_addresses_dns: "{{ consul_conf_client_addr }}"
consul_conf_addresses_http: "{{ hostvars[inventory_hostname]['ansible_' + bind_interface].ipv4.address }}"
consul_conf_addresses_https: "{{ hostvars[inventory_hostname]['ansible_' + bind_interface].ipv4.address }}"
consul_conf_addresses_rpc: "{{ consul_conf_client_addr }}"
consul_conf_data_dir: "{{ consul_data_path }}"
consul_conf_log_level: 'info'
consul_enable_syslog: true
consul_conf_node_name: "{{ consul_install_mode }}-{{ ansible_hostname | regex_replace('\\.', '_') }}"
consul_conf_leave_on_terminate: true
consul_conf_retry_interval: 30s
consul_conf_disable_update_check: true