---
pip_version_pip: latest
pip_version_setuptools: latest
pip_version_six: 1.4
pip_version_docker_py: 1.1.0

pip_extra_args: ""
proxy_env: {}

docker_registry_host: "dreg.org"
docker_registry_ip: "{{ hostvars[inventory_hostname]['ansible_' + bind_interface].ipv4.address }}"
docker_registry_with_ssl: yes
docker_registry_port: 443

docker_registry_users:
  - name: docker
    password: changeit