---
- include: Debian.yml
  when: ansible_os_family == 'Debian'

- include: RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: consul.yml

- include: webui.yml
  when: consul_install_webui | bool == True
