---
- name: Install Mesos
  yum: name="mesos-{{ mesos_version }}" state=installed

- name: Configure Zookeeper Servers
  template:
    src: zk_list.j2
    dest: /etc/mesos/zk
    owner: root
    group: root
    mode: 0644