---
- name: Check docker version
  shell: docker --version
  register: docker_version

#- debug: msg="{{ docker_version.stdout|group('Docker\sversion\s(\d\.\d\.\d),\sbuild\s(\w*)', 1) }}"

- name: Install Docker Registry v2 for Debian
  include: docker-registry-v2.yml
  when: ansible_os_family == "Debian" and docker_version.stdout|group('Docker\sversion\s(\d\.\d\.\d),\sbuild\s(\w*)', 1)|version_compare(1.6, '>=')

- name: Install Docker Registry v2 for RedHat
  include: docker-registry-v2.yml
  when: ansible_os_family == "RedHat" and docker_version.stdout|group('Docker\sversion\s(\d\.\d\.\d).*,\sbuild\s(\w*)', 1)|version_compare(1.6, '>=')

- name: Install Docker Registry v1 for Debian or RedHat
  include: docker-registry-v1.yml
  when: ansible_os_family == "Debian" and docker_version.stdout|group('Docker\sversion\s(\d\.\d\.\d),\sbuild\s(\w*)', 1)|version_compare(1.6, '<')

- name: Install Docker Registry v1 for RedHat
  include: docker-registry-v1.yml
  when: ansible_os_family == "RedHat" and docker_version.stdout|group('Docker\sversion\s(\d\.\d\.\d).*,\sbuild\s(\w*)', 1)|version_compare(1.6, '<')
